config/routes.rb
Rails.application.routes.draw do

  # Préfixe l'URL par la locale
  scope '(:locale)', :locale => /en|fr/ do

    # Routes need authentification
    authenticate :user do
      root :to => 'home#index'
      get 'home/index'

      # Routes for projet edit/new
      get     '/projets'           => 'projets#index'
      get     '/projets/new'       => 'projets#new',                as: 'new_projets'
      post    '/projets/new'       => 'projets#create',             as: 'create_projets'
      get     '/projets/:id/edit'  => 'projets#edit',               as: 'edit_projet'
      patch   '/projets/:id'       => 'projets#update',             as: ''
      put     '/projets/:id'       => 'projets#update',             as: ''
      delete  '/projets/delete'    => 'projets#destroy'

      # Routes for actions new/delete
      post    '/actions/new'                => 'actions#create',             as: 'create_actions'
      get     '/actions/:id'                => 'actions#get_actions',        as: 'get_actions'
      delete  '/actions/delete'             => 'actions#destroy'
      put     '/actions/edit'               => 'actions#set_archived'        # Set is-archived a TRUE
      put     '/actions/:id/edit/priority'  => 'actions#set_priority'        # Set priority

      # Routes for actions of projet
      get     '/projets/:id/actions/complete' => 'projets#get_actions_complete', as: 'complete_actions'

      # Routes for priorities
      get     '/projets/:id/priority'             => 'priority#index'
      post    '/projets/:id/priority/new'         => 'priority#create',     as: 'create_priority'
      put     '/projets/:id/priority/:id/edit'    => 'priority#update',     as: 'edit_priority'
      delete  '/projets/:id/priority/:id/delete'  => 'priority#destroy',    as: 'destroy_priority'

      # Routes for Amistad
      post    '/users/add/relation'               => 'users#send_request'
      put     '/users/confirm/relation'           => 'users#confirm_request'
      delete  '/users/delete/relation'            => 'users#delete_relation'
      delete  '/users/delete/request'             => 'users#delete_request'

      # Routes for sending mail
      post    '/users/send/mail'                  => 'users#send_email'

      # Routes for query filters
      get     '/:q'                               => 'actions#queries_filter'
    end

    # Override controller
    devise_for :users, :controllers => { registrations: 'registrations' }
  end

end

app/models/projet.rb
class Projet < ActiveRecord::Base
  # Validations
  validates  :name,
             presence: true

  # Mapping relation
  has_many :users, through: :user_affectations
  ### Drop cascade ###
  has_many :user_affectations, :dependent => :delete_all
  has_many :actions, :dependent => :delete_all
  has_many :priority, :dependent => :delete_all

  ### Scopes ###

  ##
  # Load projet by projet_id
  #
  # @param : projet_id
  # @return : @projet
  ##
  def self.by_projet_id(projet_id)
    where(id: projet_id)
  end

  ##
  # Get the admin id of projet
  #
  # @param : projet_id
  # @return : int
  ##
  def self.get_admin_projet(projet_id)
    select('created_by_id').where(id: projet_id)
  end


  ##
  # Get the project affected to user
  #
  # @param : user_id
  # @return : @projets
  ##
  def self.get_user_affectations(user_id)
    joins(:user_affectations).where(:user_affectations => { user_id: user_id})
  end
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  attr_accessor :projet

  before_action :set_projet, only: %i(edit update)

  def index

  end

  def show

  end

  ##
  # Prepare object for new projet
  #
  # GET /projets/new
  # @return : @users
  ##
  def new
    @projet = Projet.new
    @users = User.all
  end

  ##
  # Save new projet
  #
  # POST /projets/new
  # Redirect to : root_path with notification success
  ##
  def create
    @projet = Projet.new(projet_params)
    @projet.created_by_id = current_user.id

    userids = params.require(:projet).permit(user_ids: [])
    userids = userids['user_ids'].first.split(',')

    if @projet.save
      Priority.set_default_properties(@projet.id)
      UserAffectation.assigned_to_project(userids, @projet.id)
      flash[:success] = t('controllers.projets.hello_flash', user: current_user.login, projet: @projet.name)
      redirect_to root_path
    else
      flash[:success] = ''
      render 'new'
    end
  end

  ##
  # @DEPRECATED
  # Edit projet by id
  #
  # GET /projets/1/edit
  ##
  def edit
    @users = User.all
  end


  ##
  # Delete projet by id
  #
  # DELETE /projets/delete
  ##
  def destroy
    if request.xhr?
      if Projet.destroy(params[:projet_id])
        response = { 'status'   => 'success'}
      else
        response = { 'status'   => 'error'}
      end
      get_response(response)
    end
  end


  ##
  # Load all complete action by projet
  #
  # GET /projets/1/actions/complete
  ##
  def get_actions_complete
    @actions = Action.get_complete_actions_by_projet(params[:id])
    render 'projets/archive'
  end



  ### PRIVATE ###
  private

  def set_projet
    @projet = Projet.by_projet_id(params[:id])
  end

  def projet_params
    params.require(:projet).permit(:name, :description)
  end
end

app/views/projets/_delete.html.erb
<button type="button" class="btn btn-delete-projet" id="btn-delete-projet"><%= t('views.projets.delete.button')%></button>

app/views/projets/_form.html.erb
<%= simple_form_for @projet, :html => {:class => 'form-manage', :id => 'formAddProjet', :method => :post}, :url => create_projets_path do | f | %>
    <div class="row">
      <div class="side-left">
        <div class="input-field">
          <%= f.label :name, t('views.projets.new.label_name')+' :' %>
          <%= f.text_field :name, class: 'ipt-name-project' %>
        </div>

        <div class="input-field">
          <%= f.label :description, t('views.projets.new.label_description')+' :'  %>
          <%= f.text_area :description, class: 'ipt-description', size: '30x10' %>
        </div>
      </div>

      <div class="side-right">
        <div class="input-field">
          <label for="ipt-description"><%= t('views.projets.new.label_collaborator')%> :</label>
          <div class="select-users" id="select-users"></div>
          <ul id="userlists">
            <% if @users.length > 0 %>
                <% @users.each do | user | %>
                    <li id="<%= user.id %>"><%= user.login %></li>
                <% end %>
            <% else %>
                <li>Pas d'utilisateurs inscrits</li>
            <% end %>
          </ul>
          <div style="display: none"><%= f.association :users %></div>
          <span class="tooltip"><span class="stars">*</span><%= t('views.projets.new.label_tips')%></span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="form-footer">
        <div class="input-field"><%= f.button :submit, t('views.projets.new.btn_submit') %></div>
      </div>
    </div>

    <% if @projet.created_by_id == current_user.id %>
        <span>yo</span>
    <% end %>
<% end %>

app/views/projets/_index.html.erb
<div class="aside" id="aside">
  <div class="btn-team">
    <div class="btn-wrapper" id="btn-details"><span></span></div>
  </div>
  <div class="team-details">
    <h1><%= t('views.layout.application.title_project')%> :</h1>
    <h2 id="title_project">Le nom du projet</h2>
    <div class="team-description">
      <h3>Description:</h3>
      <p id="team-info"></p>
    </div>
    <div class="team-collaborators">
      <h3><%= t('views.layout.application.collaborators')%> :</h3>
      <div class="collaborators" id="collaborators"></div>
    </div>
    <div class="workflow">
      <div class="action-onprogress">
        <span><%= t('views.layout.application.actions_on_working')%>:</span>
        <span id="nb_current_actions" data-action='0'></span>
      </div>
      <div class="action-finished">
        <span><%= t('views.layout.application.actions_is_finish')%>:</span>
        <span id="nb_finish_actions" data-action='0'></span>
      </div>
    </div>
  </div>
</div>

app/views/projets/_link.html.erb
<div>
  <%= link_to '', new_projets_path, class: 'btn btn-create' %>
  <%= link_to t('views.home.index.libelle_button_project'), new_projets_path, class: 'span-create' %>
</div>

app/views/projets/_select.html.erb
<div class="todolist-project">
  <div class="current-project">
    <span class="title"><%= t('views.home.index.title_project')%> :</span>
    <div class="project">
      <span class="current btn-project" id="current" data-key="default"><%= t('views.home.index.libelle_default')%></span>
      <div class="projects" id="projects">
        <ul>
          <li id="default"><%= t('views.home.index.libelle_default')%></li>
          <% @projets.each do | projet | %>
              <li id="<%= projet.id %>"><%= projet.name %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/projets/archive.html.erb
<div class="content content-index">
  <div class="todo-archieve todolist" id="todolist">
    <div id="actions-wrapper">
      <div class="actions-date">
        <% current = 'bonjour' %>
        <% @actions.each do | action | %>
            <% if current != action.created_at.to_s(:created_at) %>
                <span><%= action.created_at.to_s(:created_at) %></span>
            <% end %>
            <div class="actions">
              <div class="action is-archived" id="todo_<%= action.created_at.to_s(:created_at) %>">
                <input type="checkbox" name="checkbox" id="checkbox_<%= action.id%>">
                <label for="checkbox_<%= action.id%>"><s><%= action.contenu %></s></label>
              </div>
            </div>
            <% current = action.created_at.to_s(:created_at) %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projets/edit.html.erb
<div class="content content-manage-team">
  <h1><%= t('views.projets.new.title')%></h1>

  <%= render "projets/form" %>

</div>

app/views/projets/new.html.erb
<div class="content content-manage-team">
  <h1><%= t('views.projets.new.title')%></h1>

  <%= render "projets/form" %>
</div>